### ISSUE TITLE
looking forward to your code

### ISSUE THREAD

**Issue by Bovey0809** [XingangPan/GAN2Shape#1]
I'm quite interested in your paper, and can't wait for the code come out. Thanks for your wonderful work.

**Comment by XingangPan** [comment]
@Bovey0809 Thanks for your interest. The code is expected to be released on Jan. 2021.

**Comment by forkbabu** [comment]
@XingangPan any updates to the code :) ?

**Comment by XingangPan** [comment]
@forkbabu Thanks for your interest. Due to some conflicts in my personal schedule, the code shall be ready a little bit later than expected. I am now starting to refine the code, and it shall be done in about 2 weeks. Thanks for your patience : )

**Comment by yanistazi** [comment]
Great paper, looking forward to play with the code ! @XingangPan

**Comment by JasonBoy1** [comment]
have you finished it? Looking forward to it!

**Comment by leelang7** [comment]
i m waiting

**Comment by leelang7** [comment]
i dont know this errer.... FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/GAN2Shape/gan2shape/stylegan2/stylegan2-pytorch/lpips/weights/v0.1/vgg.pth'

**Comment by XingangPan** [comment]
@leelang7 Thanks for your feedback. This should have been fixed.

**Comment by XingangPan** [comment]
The code has been released! 
Feel free to let me know if you encounter any problems with this code :-)
