### ISSUE TITLE
How to save images for synface pre-training

### ISSUE THREAD

**Issue by jun1byte** [XingangPan/GAN2Shape#14]
Hi, may I know how can I save the images in synface pre-training? As what I have seen, the save_results function in model.py is coded in a way to receive one image path and generate image accordingly. But in the synface pre-training, a list of image paths is presented to the save_results function instead, I suspect it may be caused by the joint_train = true. 

Is there a way that your code for the save_results function can be changed to save images from joint training or the function was never intended to save images from joint training? Does that mean I need to write my own code to generate images from synface pre-training?

![image](https://user-images.githubusercontent.com/66671454/115975194-9b88b700-a55a-11eb-8ed2-b70fe1d398db.png)

Error encountered:
![image](https://user-images.githubusercontent.com/66671454/115975315-9b3ceb80-a55b-11eb-910a-87b38019178d.png)

**Comment by XingangPan** [comment]
@jun1byte Hi, you may check out the `visualize_results` function in model.py, which saves some images in tensorboard.

**Comment by jun1byte** [comment]
got it, thanks!
