### ISSUE TITLE
How to change symmetry assumption

### ISSUE THREAD

**Issue by jun1byte** [XingangPan/GAN2Shape#15]
Hi, in your report "DO 2D GANS KNOW 3D SHAPE? UNSUPERVISED 3D SHAPE RECONSTRUCTION FROM 2D IMAGE GANS", you have presented results for training without symmetry assumption (Image1 and Image2). May I know which part of the code allows me to change the "symmetry assumption"? Thanks in advance!

Image 1:
![image](https://user-images.githubusercontent.com/66671454/116829557-41ac7080-ab9c-11eb-8df2-8ebb7b5a588f.png)

Image 2:
![image](https://user-images.githubusercontent.com/66671454/116829576-57219a80-ab9c-11eb-9406-0d3108c8e6a1.png)

**Comment by XingangPan** [comment]
@jun1byte Hi, setting 'flip1' and 'flip3' to false in the config file will do.

**Comment by jun1byte** [comment]
Hi, thank you for your reply. In the synface_pretrain.yml, you have the following as the default settings:
flip1_cfg: [false, true, true, true, true, true, true, true]
flip3_cfg: [true, true, true, true, true, true, true, true]

1) May I know why do you set the first stage: flip1 = false, flip3 = true and the rest of the stages all true?

2) What does setting flip1 and flip3 mean? 

3) If I were to train the model with no symmetry assumption, do I only change the first stage of flip1 and flip3 to false (as shown below)?
flip1_cfg: [false, true, true, true, true, true, true, true]
flip3_cfg: [false, true, true, true, true, true, true, true]

4) Or should I set the flip1 and flip3 for all stages for be false (as shown below)?
flip1_cfg: [false, false, false, false, false, false, false, false]
flip3_cfg: [false, false, false, false, false, false, false, false]

**Comment by XingangPan** [comment]
@jun1byte 
1. At the beginning, the pose of each image is unknown, in which case setting flip1=True would lead to inaccurate albedo. flip3 is used in step3, in which case setting flip3=True would motivate the viewpoint network to discover the canonical viewpoint.
2. Flipping means flipping the original predictions (albedo and depth), and concat them to the original ones. As mentioned in this paper: https://arxiv.org/abs/1911.11130 
3. You should set the flip1 and flip3 for all stages to be false.

**Comment by jun1byte** [comment]
Understood, thanks!
