### ISSUE TITLE
How to change shape prior 

### ISSUE THREAD

**Issue by jun1byte** [XingangPan/GAN2Shape#16]
Hi, in your paper you have mentioned the "Effects of different shape prior" (as shown in image below). May I know at which part of the code refers to that experiment? 

May I know what code changes do I need to make in order to replicate the experiments (shown in image) carried out?

![image](https://user-images.githubusercontent.com/66671454/117070781-21102200-ad26-11eb-9d2b-8185fab62eb0.png)

**Comment by XingangPan** [comment]
@jun1byte You need to revise the `init_ellipsoid` function in gan2shape/model.py.
```
            c_x = (max_x + min_x) / 2
            c_y = (max_y + min_y) / 2
            radius = 0.4
            near = self.cfgs.get('prior_near', 0.91)
            far = self.cfgs.get('prior_far', 1.02)
```
For example, you may add a value to `c_x` to shift the ellipsoid, or you may set `far = 0.96` to make a weak prior.
