### ISSUE TITLE
About pre-training

### ISSUE THREAD

**Issue by 07hyx06** [XingangPan/GAN2Shape#2]
Thanks for your great work!

What about the results of pre-training on the whole dataset (e.g. CelebA) and test on one unseen image without any optimization?  Just like the setting in Unsup3D.

**Comment by XingangPan** [comment]
@07hyx06 I haven't tried that. But if we pre-train on only 200 samples and test on an unseen image without optimization, the result would be coarse without details. I guess pre-training on the whole dataset would get better results, but not as precise as the result with instance-specific optimization.
