### ISSUE TITLE
Excuse me, I want to ask you a question

### ISSUE THREAD

**Issue by huyu-coder** [XingangPan/GAN2Shape#22]
Hello,XingangPan！I feel that your method is very perfect, for 3D reconstruction tasks, in addition to the two evaluation indicators of MAD, SIDE to evaluate the quality of the model, and other evaluation indicators can be used as the evaluation criteria,I really want to write a new paper. I really want to write a new paper. In the case of studying your papers, can you think from other points? 
I am looking forward to your reply.Thanks!

**Comment by XingangPan** [comment]
@huyu-coder Hi, thanks for your interest in this work. Our work uses a depth map to represent a 3D shape, which is somewhat limited. One extension is to use a full 3D representation like a 3D mesh instead.

**Comment by huyu-coder** [comment]
> @huyu-coder Hi, thanks for your interest in this work. Our work uses a depth map to represent a 3D shape, which is somewhat limited. One extension is to use a full 3D representation like a 3D mesh instead.

I saw that the article of unsup3d is to save the 3D reconstructed shape in. Obj format. Is 3D mesh displayed in obj format? Do you mean to use your method to reconstruct the shape, then save it in obj format and display it in 3D？

**Comment by huyu-coder** [comment]
> > @huyu-coder Hi, thanks for your interest in this work. Our work uses a depth map to represent a 3D shape, which is somewhat limited. One extension is to use a full 3D representation like a 3D mesh instead.
> 
> I saw that the article of unsup3d is to save the 3D reconstructed shape in. Obj format. Is 3D mesh displayed in obj format? Do you mean to use your method to reconstruct the shape, then save it in obj format and display it in 3D？

Thank you very much for your answers and guidance

**Comment by huyu-coder** [comment]
> @huyu-coder Hi, thanks for your interest in this work. Our work uses a depth map to represent a 3D shape, which is somewhat limited. One extension is to use a full 3D representation like a 3D mesh instead.
