### ISSUE TITLE
a question on pre-trained checkpoints

### ISSUE THREAD

**Issue by yzliu567** [XingangPan/GAN2Shape#25]
Hi, your pipeline is very interesting. But I'm wondering how pre-trained networks are used here. Since you are trying to train(or do optimization) on each new image, why do you need to pretrain your network on some instances?

**Comment by XingangPan** [comment]
@yzliu567 Even with pretrained models, you still need to train on each new image. The goal of the pretrained models is to provide a coarse initialization so that the results of the instance-specific training would be more robust.

**Comment by yzliu567** [comment]
@XingangPan I see. Thank you.
