### ISSUE TITLE
BUG in calculating l2 regularization?

### ISSUE THREAD

**Issue by syguan96** [XingangPan/GAN2Shape#28]
Hi @XingangPan, Thanks for your contribuution. The implementation of l2 regularization on \delta_w is very fancy. But it seems that your code is inconsistent in the description of the appendix.

In appendix,  `E(I) and F_2(0)` will be input into `F_1`, as shown in the following:
![image](https://user-images.githubusercontent.com/81640539/125959734-df94e436-bd76-481e-8fda-4be0b30cae5e.png)

However, in your coder, `F_2(0)` is calculated by the later `8-self.F1_d` FC layers, and `hidden` (\ie `E(I)` + `F_2`(0)) also is input into the later `8-self.F1_d` FC layers. It means that `F_1` is actually same as `F_2`?

```
self.center_h = self.generator.style_forward(torch.zeros(1, self.z_dim).cuda(), depth=8-self.F1_d)
```

```
hidden = offset + self.center_h
offset = self.generator.style_forward(hidden, skip=8-self.F1_d) - self.center_w
```

**Comment by XingangPan** [comment]
Hi @syguan96  Note that the arguments of the two cases are different. 
`self.center_h = self.generator.style_forward(torch.zeros(1, self.z_dim).cuda(), depth=8-self.F1_d)`
Here `depth=n` means using the first n layers to compute.
`offset = self.generator.style_forward(hidden, skip=8-self.F1_d) - self.center_w`
Here `skip=n` means skipping the first n layers and using the remaining layers to compute.

**Comment by syguan96** [comment]
Opzz, Thanks for your clarify! It's my fault. Sorry...
