### ISSUE TITLE
What if we used a W+ latent space projection?

### ISSUE THREAD

**Issue by vkkong** [XingangPan/GAN2Shape#29]
I'm considering trying this out with w+ projection, so instead of the [1,512] latent space a [14,512] latent space so that the projected image matches more closely to the input image. Do you foresee any problems with this ?

One thing I'm concerned about is that W+ space projections tend to match very closely with the input image. Even if the input image is outside the original distribution it's trained on. Eg: From [Image2StyleGAN](https://arxiv.org/pdf/1904.03189.pdf), an FFHQ stylegan model can project a car in W+

> Going beyond faces, interestingly, we find that although
the StyleGAN generator is trained on a human face dataset,
the embedding algorithm is capable to go far beyond human faces. As Figure 1 shows, although slightly worse
than those of human faces, we can obtain reasonable and
relatively high-quality embeddings of cats, dogs and even
paintings and cars. This reveals the effective embedding capability of the algorithm and the generality of the learned
filters of the generator

So wondering if that would make the "pseudo samples" and "projected samples" too close for the model to learn anything meaningful via reconstruction loss.

I look forward to hearing your thoughts on this. What do you think ?

**Comment by XingangPan** [comment]
Hi, @vkkong  My concern is exactly what you have mentioned. In this work, we need to rely on the image prior of GAN. But using the W+ space would risk losing such prior, as the "projected samples" would be too close to the "pseudo samples".

**Comment by vkkong** [comment]
Thanks for the response, Xingang. Makes sense!
