### ISSUE TITLE
StyleGAN2 pretrained weights

### ISSUE THREAD

**Issue by FrancisYu2020** [XingangPan/GAN2Shape#9]
Hi Xingang,

To get the latent file I checked the GitHub repo you referred to and thanks for letting us know such a good resource. But currently, I have some trouble with styleGAN2 pre-trained weights in PyTorch. I somehow could not run the convert_weight.py in that repo and I searched a lot only to find a reliable pretrained PyTorch weights on FFHQ dataset. So would you mind sharing the converted styleGAN2 weights on datasets that you used in your paper? I would really appreciate it. Thanks in advance!

**Comment by XingangPan** [comment]
@FrancisYu2020 The provided script `sh scripts/download.sh` would download the StyleGAN2 weights in our experiments.

**Comment by FrancisYu2020** [comment]
Sorry for asking a dumb question. I didn't realize it was already there hmmmm.... Thanks a lot!
